SEED_INSTITUTIONS = [
    {
        "id": 1,
        "name": "上海交通大学医学院附属瑞金医院",
        "institution_type": "医院",
        "region": "上海",
        "official_url": "https://www.rjh.com.cn/",
        "listing_url": "fixture://institution/1",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 2,
        "name": "北京协和医院",
        "institution_type": "医院",
        "region": "北京",
        "official_url": "https://www.pumch.cn/",
        "listing_url": "fixture://institution/2",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 3,
        "name": "复旦大学公共卫生学院",
        "institution_type": "高校",
        "region": "上海",
        "official_url": "https://sph.fudan.edu.cn/",
        "listing_url": "fixture://institution/3",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 4,
        "name": "中国医学科学院基础医学研究所",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.imm.ac.cn/",
        "listing_url": "fixture://institution/4",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 5,
        "name": "中山大学附属第一医院",
        "institution_type": "医院",
        "region": "广东",
        "official_url": "https://www.fahsysu.org.cn/",
        "listing_url": "fixture://institution/5",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 6,
        "name": "四川大学华西医院",
        "institution_type": "医院",
        "region": "四川",
        "official_url": "https://www.wchscu.cn/",
        "listing_url": "fixture://institution/6",
        "crawl_strategy": "fixture",
        "enabled": True,
    },
    {
        "id": 7,
        "name": "浙江大学医学院附属第二医院",
        "institution_type": "医院",
        "region": "浙江",
        "official_url": "https://www.z2hospital.com/",
        "listing_url": "https://www.z2hospital.com/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 8,
        "name": "华中科技大学同济医学院附属同济医院",
        "institution_type": "医院",
        "region": "湖北",
        "official_url": "https://www.tjh.com.cn/",
        "listing_url": "https://www.tjh.com.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 9,
        "name": "南京鼓楼医院",
        "institution_type": "医院",
        "region": "江苏",
        "official_url": "https://www.njglyy.com/",
        "listing_url": "https://www.njglyy.com/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 10,
        "name": "中国医学科学院肿瘤医院",
        "institution_type": "医院",
        "region": "北京",
        "official_url": "https://www.cicams.ac.cn/",
        "listing_url": "https://www.cicams.ac.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 11,
        "name": "北京大学医学部",
        "institution_type": "高校",
        "region": "北京",
        "official_url": "https://www.bjmu.edu.cn/",
        "listing_url": "https://www.bjmu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 12,
        "name": "上海交通大学医学院",
        "institution_type": "高校",
        "region": "上海",
        "official_url": "https://www.shsmu.edu.cn/",
        "listing_url": "https://www.shsmu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 13,
        "name": "浙江大学医学院",
        "institution_type": "高校",
        "region": "浙江",
        "official_url": "https://www.cmm.zju.edu.cn/",
        "listing_url": "https://www.cmm.zju.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 14,
        "name": "中南大学湘雅医学院",
        "institution_type": "高校",
        "region": "湖南",
        "official_url": "https://xysm.csu.edu.cn/",
        "listing_url": "https://xysm.csu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 15,
        "name": "广州医科大学",
        "institution_type": "高校",
        "region": "广东",
        "official_url": "https://www.gzhmu.edu.cn/",
        "listing_url": "https://www.gzhmu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 16,
        "name": "中国科学院上海药物研究所",
        "institution_type": "研究机构",
        "region": "上海",
        "official_url": "https://www.simm.ac.cn/",
        "listing_url": "https://www.simm.ac.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 17,
        "name": "中国科学院生物物理研究所",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.ibp.cas.cn/",
        "listing_url": "https://www.ibp.cas.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 18,
        "name": "国家心血管病中心",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.nccd.org.cn/",
        "listing_url": "https://www.nccd.org.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 19,
        "name": "中国疾病预防控制中心",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.chinacdc.cn/",
        "listing_url": "https://www.chinacdc.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 20,
        "name": "国家卫生健康委科学技术研究所",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.nrifp.org.cn/",
        "listing_url": "https://www.nrifp.org.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 21,
        "name": "南方医科大学南方医院",
        "institution_type": "医院",
        "region": "广东",
        "official_url": "https://www.nfyy.com/",
        "listing_url": "https://www.nfyy.com/job/gkzp/a_121553.html",
        "crawl_strategy": "nfyy",
        "enabled": True,
    },
    {
        "id": 22,
        "name": "山东大学齐鲁医院",
        "institution_type": "医院",
        "region": "山东",
        "official_url": "https://www.qiluhospital.com/",
        "listing_url": "https://www.qiluhospital.com/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 23,
        "name": "首都医科大学宣武医院",
        "institution_type": "医院",
        "region": "北京",
        "official_url": "https://www.xwhosp.com.cn/",
        "listing_url": "https://www.xwhosp.com.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 24,
        "name": "天津医科大学总医院",
        "institution_type": "医院",
        "region": "天津",
        "official_url": "https://www.tjmugh.com.cn/",
        "listing_url": "https://www.tjmugh.com.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 25,
        "name": "重庆医科大学附属第一医院",
        "institution_type": "医院",
        "region": "重庆",
        "official_url": "https://www.hospital-cqmu.com/",
        "listing_url": "https://www.hospital-cqmu.com/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 26,
        "name": "温州医科大学附属眼视光医院",
        "institution_type": "医院",
        "region": "浙江",
        "official_url": "https://www.eye.ac.cn/",
        "listing_url": "https://www.eye.ac.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 27,
        "name": "哈尔滨医科大学",
        "institution_type": "高校",
        "region": "黑龙江",
        "official_url": "https://www.hrbmu.edu.cn/",
        "listing_url": "https://www.hrbmu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 28,
        "name": "南京医科大学",
        "institution_type": "高校",
        "region": "江苏",
        "official_url": "https://www.njmu.edu.cn/",
        "listing_url": "https://www.njmu.edu.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 29,
        "name": "中国中医科学院",
        "institution_type": "研究机构",
        "region": "北京",
        "official_url": "https://www.catcm.ac.cn/",
        "listing_url": "https://www.catcm.ac.cn/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
    {
        "id": 30,
        "name": "上海市公共卫生临床中心",
        "institution_type": "医院",
        "region": "上海",
        "official_url": "https://www.shaphc.org/",
        "listing_url": "https://www.shaphc.org/",
        "crawl_strategy": "generic",
        "enabled": False,
    },
]
